### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [daominh-studio/quick-mem#18]
Please remember increasing `versionCode` with each release. v1.1 still identifies with `versionCode:1` despite of being the second release:

    package: name='com.daominh.quickmem' versionCode='1' versionName='1.1'

Background: Android uses `versionCode` to tell versions apart. To recognize newer versions as updates, `versionCode` must be higher than the one of the app already installed.

**Comment by nqmgaming** [comment]
Thank you for the reminder

**Comment by nqmgaming** [comment]
fix version code

**Comment by IzzySoft** [comment]
Now, that was fast – thanks!

May I ask what the login is needed for? Is there some web service behind it? The Readme does not say.

**Comment by IzzySoft** [comment]
Two more questions:

* Readme says it's MIT licensed, but the license file stats GPLv3. Which one is it?
* Your APKs are signed for debug. Is that intended (might be, given the releases are marked pre-release – just asking to be sure)?

**Comment by nqmgaming** [comment]
Oh, my mistake. I just changed the license from MIT to GPLv3 and unchecked the pre-release option. Currently, the application I am developing does not include website service development. However, I plan to implement it in the near future after further improving the application.

**Comment by IzzySoft** [comment]
> I just changed the license from MIT to GPLv3

Ah, great, then I got that right. Just [added your app](https://apt.izzysoft.de/packages/com.daominh.quickmem/) to my repo marking it GPLv3 as it seemed to me that was the one you intended. You can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme :smile:

> and unchecked the pre-release option

OK, then I tell my updater to ignore pre-releases from now on? The updater checkes once per day if there are new APKs to pull.

> Currently, the application I am developing does not include website service development.

The screenshots looked like. Privacy-folks prefer such things offline, so some might be "scared away" especially by the "Login with Google/Facebook" part. Maybe that can be made clearer in the app description then (just let me know what I should change – or if I should open a PR with what I've set up here so you can adjust to what you see fit. It's using Fastlane structures, so my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) can probably give you some guidance on that.

> However, I plan to implement it in the near future after further improving the application.

Will that be optional then, so the app can be used entirely offline, too, if one prefers? That would IMHO be a good thing to have, so everyone can choose as needed.

**Comment by nqmgaming** [comment]
> Ah, great, then I got that right. Just [added your app](https://apt.izzysoft.de/packages/com.daominh.quickmem/) to my repo marking it GPLv3 as it seemed to me that was the one you intended. You can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme 😄

Thank you for updating the license in your repository! Feel free to choose a badge for linking. Your contribution is much appreciated. 
> OK, then I tell my updater to ignore pre-releases from now on? The updater checkes once per day if there are new APKs to pull.

Yes, you can ignore pre-releases for now. The updater checks daily, so it should sync with the stable releases

> The screenshots looked like. Privacy-folks prefer such things offline, so some might be "scared away" especially by the "Login with Google/Facebook" part. Maybe that can be made clearer in the app description then (just let me know what I should change – or if I should open a PR with what I've set up here so you can adjust to what you see fit. It's using Fastlane structures, so my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) can probably give you some guidance on that.

I appreciate your feedback. I'll consider making the 'Login with Google/Facebook' part clearer in the app description to address privacy concerns. Thanks for your diligence!

> Will that be optional then, so the app can be used entirely offline, too, if one prefers? That would IMHO be a good thing to have, so everyone can choose as needed.

In the coming time, I will enhance the learning functionality to make it more user-friendly. Afterward, I plan to implement internet connectivity for the application and strive to ensure that it operates seamlessly both online and offline.

**Comment by IzzySoft** [comment]
> Feel free to choose a badge for linking.

Hehe, that was a hint for you. As there are badges for PlayStore and the Apple Store, the Galaxy store, the Huawei App Gallery, the Amazon Store and whats-not, there're [badges available for IzzyOnDroid](https://gitlab.com/IzzyOnDroid/repo/-/tree/master/assets), e.g. this one:

<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" width="250" alt="IzzyOnDroid Badge" align="center">

> Yes, you can ignore pre-releases for now.

Config updated accordingly, thanks!

> clearer in the app description

My offer stands to send you a PR with Fastlane structures (basically, description and graphics located in a defined directory structure starting with `/fastlane/metadata/android` as outlined in my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)) with what I've set up here. Just let me know if you want to have it. My updater would then check that as well whenever a new version of the app is pulled.

> strive to ensure that it operates seamlessly both online and offline

Great, thanks!
